github.com:
    users:
        GraydonCharlesCory:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: GraydonCharlesCory
